=== Spectyte5/Engineer_Thesis/Engineer_Thesis/JSON_files/Schema/schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "Schema for Orbital Library",
  "type": "object",
  "default": {},
  "required": [
    "ship",
    "planets",
    "control",
    "data"
  ],
  "properties": {
    "ship": {
      "type": "object",
      "default": {},
      "title": "The ship Schema",
      "required": [
        "name",
        "position",
        "velocity",
        "mass",
        "fuel",
        "fuel_usage"
      ],
      "properties": {
        "name": {
          "type": "string",
          "default": "",
          "title": "The name Schema",
          "examples": [
            "Normandy"
          ]
        },
        "position": {
          "type": "array",
          "default": [],
          "title": "The position Schema",
          "items": {
            "type": "number",
            "title": "A Schema",
            "examples": [
              0.0
            ]
          },
          "minItems": 3,
          "maxItems": 3,
          "examples": [
            [
              0.0,
              0.0,
              0.0
            ]
          ]
        },
        "velocity": {
          "type": "array",
          "default": [],
          "title": "The velocity Schema",
          "items": {
            "type": "number",
            "title": "A Schema",
            "examples": [
              0.0
            ]
          },
          "minItems": 3,
          "maxItems": 3,
          "examples": [
            [
              0.0,
              0.0,
              0.0
            ]
          ]
        },
        "mass": {
          "type": "number",
          "default": 0.0,
          "title": "The mass Schema",
          "examples": [
            10000.0
          ]
        },
        "fuel": {
          "type": "number",
          "default": 0.0,
          "title": "The fuel Schema",
          "examples": [
            5000.0
          ]
        },
        "fuel_usage": {
          "type": "number",
          "default": 0.0,
          "title": "The fuel_usage Schema",
          "examples": [
            10.0
          ]
        }
      },
      "examples": [
        {
          "name": "Normandy",
          "position": [
            0.0,
            0.0,
            0.0
          ],
          "velocity": [
            0.0,
            0.0,
            0.0
          ],
          "mass": 10000.0,
          "fuel": 5000.0,
          "fuel_usage": 10.0
        }
      ]
    },
    "planets": {
      "type": "array",
      "default": [],
      "title": "The planets Schema",
      "items": {
        "type": "object",
        "title": "A Schema",
        "required": [
          "name",
          "mass",
          "radius",
          "position"
        ],
        "minItems": 0,
        "properties": {
          "name": {
            "type": "string",
            "title": "The name Schema",
            "examples": [
              "Eol",
              "Loki",
              "Anders"
            ]
          },
          "mass": {
            "type": "number",
            "title": "The mass Schema",
            "examples": [
              1000000.0,
              2000000.0,
              3000000.0
            ]
          },
          "radius": {
            "type": "number",
            "title": "The radius Schema",
            "examples": [
              5000.0,
              7000.0,
              6000.0
            ]
          },
          "position": {
            "type": "array",
            "title": "The position Schema",
            "items": {
              "type": "number",
              "title": "A Schema",
              "examples": [
                10000.0,
                200.0,
                200000.0,
                2000.0,
                300000.0,
                300.0
              ]
            },
            "minItems": 3,
            "maxItems": 3,
            "examples": [
              [
                10000.0,
                10000.0,
                10000.0
              ],
              [
                200.0,
                200000.0,
                2000.0
              ],
              [
                300000.0,
                300.0,
                300000.0
              ]
            ]
          }
        },
        "examples": [
          {
            "name": "Eol",
            "mass": 1000000.0,
            "radius": 5000.0,
            "position": [
              10000.0,
              10000.0,
              10000.0
            ]
          },
          {
            "name": "Loki",
            "mass": 2000000.0,
            "radius": 7000.0,
            "position": [
              200.0,
              200000.0,
              2000.0
            ]
          },
          {
            "name": "Anders",
            "mass": 3000000.0,
            "radius": 6000.0,
            "position": [
              300000.0,
              300.0,
              300000.0
            ]
          }
        ]
      },
      "examples": [
        [
          {
            "name": "Eol",
            "mass": 1000000.0,
            "radius": 5000.0,
            "position": [
              10000.0,
              10000.0,
              10000.0
            ]
          },
          {
            "name": "Loki",
            "mass": 2000000.0,
            "radius": 7000.0,
            "position": [
              200.0,
              200000.0,
              2000.0
            ]
          },
          {
            "name": "Anders",
            "mass": 3000000.0,
            "radius": 6000.0,
            "position": [
              300000.0,
              300.0,
              300000.0
            ]
          }
        ]
      ]
    },
    "control": {
      "type": "array",
      "default": [],
      "title": "The control Schema",
      "items": {
        "type": "object",
        "title": "A Schema",
        "required": [
          "starttime",
          "endtime",
          "force"
        ],
        "minItems": 0,
        "properties": {
          "starttime": {
            "type": "array",
            "title": "The starttime Schema",
            "items": {
              "type": "number",
              "title": "A Schema",
              "examples": [
                0.0,
                30.0,
                80.0,
                90.0
              ]
            },
            "minItems": 3,
            "maxItems": 3,
            "examples": [
              [
                0.0,
                0.0,
                0.0
              ],
              [
                30.0,
                30.0,
                30.0
              ],
              [
                80.0,
                80.0,
                90.0
              ]
            ]
          },
          "endtime": {
            "type": "array",
            "title": "The endtime Schema",
            "items": {
              "type": "number",
              "title": "A Schema",
              "examples": [
                10.0,
                60.0,
                100.0
              ]
            },
            "minItems": 3,
            "maxItems": 3,
            "examples": [
              [
                10.0,
                10.0,
                10.0
              ],
              [
                60.0,
                60.0,
                60.0
              ],
              [
                100.0,
                100.0,
                100.0
              ]
            ]
          },
          "force": {
            "type": "array",
            "title": "The force Schema",
            "items": {
              "type": "number",
              "title": "A Schema",
              "examples": [
                200.0,
                100.0,
                0.0,
                300.0
              ]
            },
            "minItems": 3,
            "maxItems": 3,
            "examples": [
              [
                200.0,
                100.0,
                0.0
              ],
              [
                0.0,
                100.0,
                300.0
              ],
              [
                100.0,
                100.0,
                100.0
              ]
            ]
          }
        },
        "examples": [
          {
            "starttime": [
              0.0,
              0.0,
              0.0
            ],
            "endtime": [
              10.0,
              10.0,
              10.0
            ],
            "force": [
              200.0,
              100.0,
              0.0
            ]
          },
          {
            "starttime": [
              30.0,
              30.0,
              30.0
            ],
            "endtime": [
              60.0,
              60.0,
              60.0
            ],
            "force": [
              0.0,
              100.0,
              300.0
            ]
          },
          {
            "starttime": [
              80.0,
              80.0,
              90.0
            ],
            "endtime": [
              100.0,
              100.0,
              100.0
            ],
            "force": [
              100.0,
              100.0,
              100.0
            ]
          }
        ]
      },
      "examples": [
        [
          {
            "starttime": [
              0.0,
              0.0,
              0.0
            ],
            "endtime": [
              10.0,
              10.0,
              10.0
            ],
            "force": [
              200.0,
              100.0,
              0.0
            ]
          },
          {
            "starttime": [
              30.0,
              30.0,
              30.0
            ],
            "endtime": [
              60.0,
              60.0,
              60.0
            ],
            "force": [
              0.0,
              100.0,
              300.0
            ]
          },
          {
            "starttime": [
              80.0,
              80.0,
              90.0
            ],
            "endtime": [
              100.0,
              100.0,
              100.0
            ],
            "force": [
              100.0,
              100.0,
              100.0
            ]
          }
        ]
      ]
    },
    "data": {
      "type": "object",
      "default": {},
      "title": "The data Schema",
      "required": [
        "time",
        "step",
        "ode"
      ],
      "properties": {
        "time": {
          "type": "number",
          "default": 0.0,
          "title": "The time Schema",
          "examples": [
            120.0
          ]
        },
        "step": {
          "type": "number",
          "default": 0.0,
          "title": "The step Schema",
          "examples": [
            1.0
          ]
        },
        "ode": {
          "type": "integer",
          "default": 0,
          "enum": [0, 1, 2, 3],
          "title": "The ode Schema",
          "examples": [
            3
          ]
        }
      },
      "examples": [
        {
          "time": 120.0,
          "step": 1.0,
          "ode": 3
        }
      ]
    }
  },
  "examples": [
    {
      "ship": {
        "name": "Normandy",
        "position": [
          0.0,
          0.0,
          0.0
        ],
        "velocity": [
          0.0,
          0.0,
          0.0
        ],
        "mass": 10000.0,
        "fuel": 5000.0,
        "fuel_usage": 10.0
      },
      "planets": [
        {
          "name": "Eol",
          "mass": 1000000.0,
          "radius": 5000.0,
          "position": [
            10000.0,
            10000.0,
            10000.0
          ]
        },
        {
          "name": "Loki",
          "mass": 2000000.0,
          "radius": 7000.0,
          "position": [
            200.0,
            200000.0,
            2000.0
          ]
        },
        {
          "name": "Anders",
          "mass": 3000000.0,
          "radius": 6000.0,
          "position": [
            300000.0,
            300.0,
            300000.0
          ]
        }
      ],
      "control": [
        {
          "starttime": [
            0.0,
            0.0,
            0.0
          ],
          "endtime": [
            10.0,
            10.0,
            10.0
          ],
          "force": [
            200.0,
            100.0,
            0.0
          ]
        },
        {
          "starttime": [
            30.0,
            30.0,
            30.0
          ],
          "endtime": [
            60.0,
            60.0,
            60.0
          ],
          "force": [
            0.0,
            100.0,
            300.0
          ]
        },
        {
          "starttime": [
            80.0,
            80.0,
            90.0
          ],
          "endtime": [
            100.0,
            100.0,
            100.0
          ],
          "force": [
            100.0,
            100.0,
            100.0
          ]
        }
      ],
      "data": {
        "time": 120.0,
        "step": 1.0,
        "ode": 3
      }
    }
  ]
}

=== Spectyte5/Engineer_Thesis/Engineer_Thesis/JSON_files/Sim6.json
{
  "control": [
    {
      "endtime": [
        0.0,
        14315.0,
        0.0
      ],
      "force": [
        0.0,
        368000.00,
        0.0
      ],
      "starttime": [
        0.0,
        14300.0,
        0.0
      ]
    },
    {
      "endtime": [
        0.0,
        33120.0,
        0.0
      ],
      "force": [
        0.0,
        -202000.0,
        0.0
      ],
      "starttime": [
        0.0,
        33105.0,
        0.0
      ]
    },
    {
      "endtime": [
        0.0,
        60238.0,
        0.0
      ],
      "force": [
        0.0,
        -50000,
        0.0
      ],
      "starttime": [
        0.0,
        60223.0,
        0.0
      ]
    }
  ],
  "data": {
    "ode": 3,
    "step": 1,
    "time": 110000
  },
  "planets": [
    {
      "name": "Earth",
      "mass": 5.972e24,
      "radius": 6.378e6,
      "orbit": false,
      "position": [
        0.0,
        0.0,
        0.0
      ]
    }
  ],
  "ship": {
    "fuel": 2000.0,
    "fuel_usage": 5.0,
    "mass": 5000.0,
    "name": "Sim6",
    "position": [
      12742000.0,
      0.0,
      0.0
    ],
    "velocity": [
      0.0,
      5592.27,
      0.0
    ]
  }
}

=== Spectyte5/Engineer_Thesis/Engineer_Thesis/JSON_files/TestCase_1.json
{
    "control": [
        {
            "endtime": [
                50.0,
                0.0,
                0.0
            ],
            "force": [
                500.0,
                0.0,
                0.0
            ],
            "starttime": [
                0.0,
                0.0,
                0.0
            ]
        }
    ],
    "data": {
        "ode": 2,
        "step": 0.1,
        "time": 50.0
    },
    "planets": [
      
    ],
    "ship": {
        "fuel": 500.0,
        "fuel_usage": 10.0,
        "mass": 10000.0,
        "name": "TestCase1",
        "position": [
            0.0,
            0.0,
            0.0
        ],
        "velocity": [
            0.0,
            0.0,
            0.0
        ]
    }
}

=== Spectyte5/Engineer_Thesis/Engineer_Thesis/JSON_files/TestCase_2.json
{
  "control": [
    {
      "endtime": [
        0.0,
        0.0,
        0.0
      ],
      "force": [
        0.0,
        0.0,
        0.0
      ],
      "starttime": [
        0.0,
        0.0,
        0.0
      ]
    }
  ],
  "data": {
    "ode": 3,
    "step": 1,
    "time": 513
  },
  "planets": [
    {
      "name": "Earth",
      "mass": 5972200000000000000000000.0,
      "radius": 6371000,
      "position": [
        0.0,
        0.0,
        0.0
      ]
    }
  ],
  "ship": {
    "fuel": 0.0,
    "fuel_usage": 0.0,
    "mass": 10000.0,
    "name": "TestCase2",
    "position": [
      6371000.0,
      0.0,
      0.0
    ],
    "velocity": [
      11200.0,
      0.0,
      0.0
    ]
  }
}

=== Spectyte5/Engineer_Thesis/Engineer_Thesis/JSON_files/TestCase_3.json
{
  "control": [
    {
      "endtime": [
        0.0,
        465.0,
        0.0
      ],
      "force": [
        0.0,
        15418.6,
        0.0
      ],
      "starttime": [
        0.0,
        0.0,
        0.0
      ]
    }
  ],
  "data": {
    "ode": 0,
    "step": 1,
    "time": 465.0
  },
  "planets": [
    {
      "name": "Moon",
      "mass": 73460000000000000000000.0,
      "radius": 1738100.0,
      "position": [
        0.0,
        0.0,
        0.0
      ]
    }
      ],
      "ship": {
        "fuel": 2350.0,
        "fuel_usage": 5.05376,
        "mass": 4500.0,
        "name": "TestCase3",
        "position": [
          0.0,
          1738100.0,
          0.0
        ],
        "velocity": [
          0.0,
          0.0,
          0.0
        ]
      }
    }

=== Spectyte5/Engineer_Thesis/Engineer_Thesis/JSON_files/TestCollistion.json
{
    "control": [
        {
            "endtime": [
                0.0,
                0.0,
                0.0
            ],
            "force": [
                0.0,
                0.0,
                0.0
            ],
            "starttime": [
                0.0,
                0.0,
                0.0
            ]
        }
    ],
    "data": {
        "ode": 3,
        "step": 10,
        "time": 550.0
    },
    "planets": [
      {
        "name": "PlanetTest",
        "mass": 100000,
        "radius": 5000,
        "position": [
          0.0,
          0.0,
          0.0
        ]
      }
  ],
    "ship": {
        "fuel": 0.0,
        "fuel_usage": 0.0,
        "mass": 1000.0,
        "name": "TestCaseCC",
        "position": [
         5000,
         0.0,
         0.0
        ],
        "velocity": [
        1000,
        0.0,
        0.0
        ]
    }
}

=== Spectyte5/Engineer_Thesis/Engineer_Thesis/JSON_files/Test4.json
{
    "control": [
        {
            "endtime": [
                20.0,
                20.0,
                20.0
            ],
            "force": [
                10.0,
                10.0,
                10.0
            ],
            "starttime": [
                10.0,
                10.0,
                10.0
            ]
        },
        {
            "endtime": [
                30.0,
                30.0,
                30.0
            ],
            "force": [
                -10.0,
                -10.0,
                -10.0
            ],
            "starttime": [
                20.0,
                20.0,
                20.0
            ]
        },
        {
            "endtime": [
                60.0,
                60.0,
                60.0
            ],
            "force": [
                5.0,
                5.0,
                5.0
            ],
            "starttime": [
                40.0,
                40.0,
                40.0
            ]
        }
    ],
    "data": {
        "ode": 2,
        "step": 0.5,
        "time": 100.0
    },
    "planets": [
        {
            "mass": 1000000.0,
            "name": "Kirkstone",
            "position": [
                20000.0,
                20000.0,
                20000.0
            ],
            "radius": 5000.0
        },
        {
            "mass": 200000.0,
            "name": "Dunfell",
            "position": [
                -10000.0,
                -10000.0,
                -10000.0
            ],
            "radius": 3000.0
        }
    ],
    "ship": {
        "fuel": 5000.0,
        "fuel_usage": 10.0,
        "mass": 15000.0,
        "name": "Test4",
        "position": [
            0.0,
            0.0,
            0.0
        ],
        "velocity": [
            10.0,
            10.0,
            10.0
        ]
    }
}
